### PR TITLE
fix resource actor type of consent granted event

### PR DESCRIPTION
**Pull request by alaincroisetiere**

### CODE REVIEW

**Comment by andrewclymer** [comment]
Thanks for your pull request,  but we don't agree with your change.  The ConsentGranted event is raised when the user grants consent from the consent UI, user interactions is involved,  not a machine.  If you think differently let me know your reasoning.

**Comment by alaincroisetiere** [comment]
I think the type of the resource actor should be machine because the resource actor identifier is a client id and it should be coherent with the [ConsentDenied event at line 18 of the adapter](https://github.com/RockSolidKnowledge/RSK.IdentityServer4.AuditEventSink/blob/5301146a6e9cf7264b3ec8d5b29d05457b3403a3/Src/Adapters/ConsentDeniedEventAdapter.cs#L18).

**Comment by alaincroisetiere** [comment]
Any update @andrewclymer ?

**Comment by alaincroisetiere** [comment]
✋

**Comment by alaincroisetiere** [comment]
✋

**Comment by alaincroisetiere** [comment]
✋

**Comment by scottbrady91** [comment]
Hi! Sorry about the delay on this. I've updated this library to support Duende IdentityServer, as well as IdentityServer4.

As part of that update, I've addressed the unusual actor and resource for consent. The consent granted and denied events now have the user as the actor type and the client application as the resource type. After all, the user is denying the application from acting on their behalf.

Thanks again for bearing with us.

**Pull request closed without merging**
